### ISSUE TITLE
Add meaningful errors to onError() ResponseListener callback method 

### ISSUE THREAD

**Issue by bohuz23** [freshbits/pathshare-sdk-android#8]
Hi, I've the following issue
I can't create session because when I'm calling 

```
Pathshare.client().saveUser(
                    user.fullName,
                    "+19999999999",
                    user.email,
                    UserType.TECHNICIAN,
                    ContextCompat.getDrawable(context, R.drawable.face),
                    object : ResponseListener {
                        override fun onSuccess() {
                            // success handling
                        }

                        override fun onError() {
                            Timber.d("Error here")
                        }
                    });
```

callback moves to onError(), but I can't figure out what causing it. 
It'd be great to have `error`  field which will tell error details. 

I'm using 2.3.1 pathshare version

**Comment by jhabr** [comment]
I assume you did enter your api key from your account into the `pathshare_account_token` field right? I'll check it.

Good point btw, we will improve the error messages. Thx for that.

**Comment by bohuz23** [comment]
@jhabr , yes. I assume it could be related to dependencies conflicts. Because I can run sample app without any issues. 
It'd be awesome if you'll add it, because for now I can't use pathshare in my app

**Comment by jhabr** [comment]
@sQuark23 We added a new [release 2.3.2](https://github.com/freshbits/pathshare-sdk-android/releases/tag/2.3.2). Please let me know if you still encounter your issue after updating.

**Comment by bohuz23** [comment]
@jhabr, thank you. I've upgraded to v2.3.2 and now I see an error. Here's what it saying 

```
java.lang.Throwable: Response code was 422. Request returned an empty body.
        at ch.freshbits.pathshare.sdk.model.d.a(:11)
        at ch.freshbits.pathshare.sdk.model.p.onResponse(:2)
        at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0$DefaultCallAdapterFactory$ExecutorCallbackCall$1(DefaultCallAdapterFactory.java:82)
        at retrofit2.-$$Lambda$DefaultCallAdapterFactory$ExecutorCallbackCall$1$3wC8FyV4pyjrzrYL5U0mlYiviZw.run(Unknown Source:6)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by jhabr** [comment]
@sQuark23 It seems that the request you're sending is not valid. When I look at it, it looks like your `email` and `phone` params are interchanged and so your email and phone are not valid. Your `saveUser` method should look like this:

```
Pathshare.client().saveUser(
                    name,
                    email,
                    phone,
                    userType,
                    image,
                    object : ResponseListener { ... }
)
```

(also see the example [here](https://github.com/freshbits/pathshare-sdk-android#kotlin-1))

Could please try to change the order of your params and see if it helps?

We are still working on adding some more meaningful error messages so that these kind of errors are more obvious.

**Comment by bohuz23** [comment]
@jhabr , yeah - it was stupid mistake with wrong arguments positioning. Now it works like a charm! Thank you so much for your help
